### PR TITLE
flatten before bordering frink in README.md

### PR DESCRIPTION
**Pull request by jsta**
I think this change is more in line with peoples' expectations of `image_border()`?

### CODE REVIEW

**Comment by jeroenooms** [comment]
The frink image only has a single layer? How can it be flattened?

**Comment by jsta** [comment]
The flattening fills transparency with white so that the border is drawn around the exterior of the image instead of filling the transparency with the border color.

**Comment by jeroenooms** [comment]
The output looks exactly identical? Not sure this make the example better.

**Comment by jsta** [comment]
It looks different to me. I will link an example is a sec.

**Comment by jsta** [comment]
http://i.imgur.com/F76eYWG.png

**Comment by jeroenooms** [comment]
Hmm interesting. In my case it only shows the border in both examples. Which platform and version of imagemagick do you run?

**Comment by jsta** [comment]
```
Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01 http://www.imagemagick.org
```
```
Distributor ID:	Ubuntu
Release:	16.04
Codename:	xenial
```

**Comment by jeroenooms** [comment]
perhaps that is a bug that was recently fixed then. I'll merge the PR and improve the example a bit more.

**Comment by jeroenooms** [comment]
By the way can you test if `image_display` works for you (both with `animate=TRUE` or `FALSE`)

**Comment by jsta** [comment]
Yes, I tested the `image_display` with the banana gif and it works for both.

**Comment by jsta** [comment]
Although I get some odd behavior with the transparent background (default) frink image. There is no control strip to close/minimize/move the popup with `image_display(frink)` but there is with
`image_display(image_flatten(frink))`

**Pull request merged**
