### PR TITLE
reveal images and animations in README

### PR DESCRIPTION
**Pull request by jennybc**
Give the people their dancing banana!

### CODE REVIEW

**Comment by jennybc** [comment]
There must be a more elegant solution but doing it the obvious way created some problems. Can this work more smoothly with rmarkdown somehow?

**Comment by jeroenooms** [comment]
Thanks. I'll try to figure out how to make `knitr` pick up on graphics that were generated outside of the graphics device.

**Comment by jeroenooms** [comment]
By the way there are more cool examples in the manual pages. I always assume people read those fist, but maybe not.

**Comment by hrbrmstr** [comment]
Aye, caught those. I've been contemplating adding a few of the images in-line into the manual examples but I'm reticent to (a) make the package size too large (since the images need to be pre-built) (b) upset CRAN with a large package size, esp with animated gifs :-). But I may still add an image or two in-line into some of the help since this is an image processing pkg and may help some folks new to the world of "[Image]magick".

**Comment by hrbrmstr** [comment]
Also, you can just use `` in the markdown bits to get knitr to pick up on said external images (i've used that occasionally w/programmaticaly generated svgs).

**Comment by jennybc** [comment]
@hrbrmstr That's what I did. But this also means you have to have hidden chunks that are writing to file, so the visible chunks look more like what a user should do. I also get intermittent Pandoc errors on this README, even with `eval = FALSE` every where, which puzzles me. It feels like Pandoc errors if it can't retrieve things quickly enough from the internet sometimes? Like badges?

@jeroenooms I look at the README to decide if / how soon to install. And even then I certainly don't systematically drill down into help files and execute examples. I think pre-baking some things really draws in people who are "just looking".

**Pull request merged**
